package com.balance.hib.bean;
// Generated 24 Jul, 2012 10:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BsGroup generated by hbm2java
 */
public class BsGroup  implements java.io.Serializable {


     private Integer bsId;
     private String bsName;
     private String bsInitial;
     private Set<BsHead> bsHeads = new HashSet<BsHead>(0);

    public BsGroup() {
    }

	
    public BsGroup(String bsName, String bsInitial) {
        this.bsName = bsName;
        this.bsInitial = bsInitial;
    }
    public BsGroup(String bsName, String bsInitial, Set<BsHead> bsHeads) {
       this.bsName = bsName;
       this.bsInitial = bsInitial;
       this.bsHeads = bsHeads;
    }
   
    public Integer getBsId() {
        return this.bsId;
    }
    
    public void setBsId(Integer bsId) {
        this.bsId = bsId;
    }
    public String getBsName() {
        return this.bsName;
    }
    
    public void setBsName(String bsName) {
        this.bsName = bsName;
    }
    public String getBsInitial() {
        return this.bsInitial;
    }
    
    public void setBsInitial(String bsInitial) {
        this.bsInitial = bsInitial;
    }
    public Set<BsHead> getBsHeads() {
        return this.bsHeads;
    }
    
    public void setBsHeads(Set<BsHead> bsHeads) {
        this.bsHeads = bsHeads;
    }




}


