package com.balance.hib.bean;
// Generated 24 Jul, 2012 10:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BsHead generated by hbm2java
 */
public class BsHead  implements java.io.Serializable {


     private Integer bsHeadId;
     private BsGroup bsGroup;
     private String bsHeadName;
     private String bsHeadInitial;
     private Set<ExpenseEntry> expenseEntries = new HashSet<ExpenseEntry>(0);
     private Set<UserAccountDetails> userAccountDetailses = new HashSet<UserAccountDetails>(0);
     private Set<BsSubHead> bsSubHeads = new HashSet<BsSubHead>(0);
     private Set<IncomeEntry> incomeEntries = new HashSet<IncomeEntry>(0);
private Set transfers = new HashSet(0);
    public Set getTransfers() {
        return transfers;
    }

    public void setTransfers(Set transfers) {
        this.transfers = transfers;
    }

    public BsHead() {
    }

	
    public BsHead(BsGroup bsGroup, String bsHeadName, String bsHeadInitial) {
        this.bsGroup = bsGroup;
        this.bsHeadName = bsHeadName;
        this.bsHeadInitial = bsHeadInitial;
    }
    public BsHead(BsGroup bsGroup, String bsHeadName, String bsHeadInitial, Set<ExpenseEntry> expenseEntries, Set<UserAccountDetails> userAccountDetailses, Set<BsSubHead> bsSubHeads, Set<IncomeEntry> incomeEntries) {
       this.bsGroup = bsGroup;
       this.bsHeadName = bsHeadName;
       this.bsHeadInitial = bsHeadInitial;
       this.expenseEntries = expenseEntries;
       this.userAccountDetailses = userAccountDetailses;
       this.bsSubHeads = bsSubHeads;
       this.incomeEntries = incomeEntries;
    }
   
    public Integer getBsHeadId() {
        return this.bsHeadId;
    }
    
    public void setBsHeadId(Integer bsHeadId) {
        this.bsHeadId = bsHeadId;
    }
    public BsGroup getBsGroup() {
        return this.bsGroup;
    }
    
    public void setBsGroup(BsGroup bsGroup) {
        this.bsGroup = bsGroup;
    }
    public String getBsHeadName() {
        return this.bsHeadName;
    }
    
    public void setBsHeadName(String bsHeadName) {
        this.bsHeadName = bsHeadName;
    }
    public String getBsHeadInitial() {
        return this.bsHeadInitial;
    }
    
    public void setBsHeadInitial(String bsHeadInitial) {
        this.bsHeadInitial = bsHeadInitial;
    }
    public Set<ExpenseEntry> getExpenseEntries() {
        return this.expenseEntries;
    }
    
    public void setExpenseEntries(Set<ExpenseEntry> expenseEntries) {
        this.expenseEntries = expenseEntries;
    }
    public Set<UserAccountDetails> getUserAccountDetailses() {
        return this.userAccountDetailses;
    }
    
    public void setUserAccountDetailses(Set<UserAccountDetails> userAccountDetailses) {
        this.userAccountDetailses = userAccountDetailses;
    }
    public Set<BsSubHead> getBsSubHeads() {
        return this.bsSubHeads;
    }
    
    public void setBsSubHeads(Set<BsSubHead> bsSubHeads) {
        this.bsSubHeads = bsSubHeads;
    }
    public Set<IncomeEntry> getIncomeEntries() {
        return this.incomeEntries;
    }
    
    public void setIncomeEntries(Set<IncomeEntry> incomeEntries) {
        this.incomeEntries = incomeEntries;
    }




}


