package com.balance.hib.bean;
// Generated 24 Jul, 2012 10:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExpenseEntry generated by hbm2java
 */
public class ExpenseEntry  implements java.io.Serializable {


     private int expenseId;
     private BsSubHead bsSubHead;
     private BsHead bsHead;
     private UserDetails userDetails;
     private UserAccountDetails userAccountDetails;
     private Date expenseDate;
     private double expenseAmount;
     private String expenseRemarks;
     private int relevantUser;

    public ExpenseEntry() {
    }

	
    public ExpenseEntry(int expenseId, BsSubHead bsSubHead, BsHead bsHead, double expenseAmount, int relevantUser) {
        this.expenseId = expenseId;
        this.bsSubHead = bsSubHead;
        this.bsHead = bsHead;
        this.expenseAmount = expenseAmount;
        this.relevantUser = relevantUser;
    }
    public ExpenseEntry(int expenseId, BsSubHead bsSubHead, BsHead bsHead, UserDetails userDetails, UserAccountDetails userAccountDetails, Date expenseDate, double expenseAmount, String expenseRemarks, int relevantUser) {
       this.expenseId = expenseId;
       this.bsSubHead = bsSubHead;
       this.bsHead = bsHead;
       this.userDetails = userDetails;
       this.userAccountDetails = userAccountDetails;
       this.expenseDate = expenseDate;
       this.expenseAmount = expenseAmount;
       this.expenseRemarks = expenseRemarks;
       this.relevantUser = relevantUser;
    }
   
    public int getExpenseId() {
        return this.expenseId;
    }
    
    public void setExpenseId(int expenseId) {
        this.expenseId = expenseId;
    }
    public BsSubHead getBsSubHead() {
        return this.bsSubHead;
    }
    
    public void setBsSubHead(BsSubHead bsSubHead) {
        this.bsSubHead = bsSubHead;
    }
    public BsHead getBsHead() {
        return this.bsHead;
    }
    
    public void setBsHead(BsHead bsHead) {
        this.bsHead = bsHead;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public UserAccountDetails getUserAccountDetails() {
        return this.userAccountDetails;
    }
    
    public void setUserAccountDetails(UserAccountDetails userAccountDetails) {
        this.userAccountDetails = userAccountDetails;
    }
    public Date getExpenseDate() {
        return this.expenseDate;
    }
    
    public void setExpenseDate(Date expenseDate) {
        this.expenseDate = expenseDate;
    }
    public double getExpenseAmount() {
        return this.expenseAmount;
    }
    
    public void setExpenseAmount(double expenseAmount) {
        this.expenseAmount = expenseAmount;
    }
    public String getExpenseRemarks() {
        return this.expenseRemarks;
    }
    
    public void setExpenseRemarks(String expenseRemarks) {
        this.expenseRemarks = expenseRemarks;
    }
    public int getRelevantUser() {
        return this.relevantUser;
    }
    
    public void setRelevantUser(int relevantUser) {
        this.relevantUser = relevantUser;
    }




}


