package com.balance.hib.bean;
// Generated 24 Jul, 2012 10:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * IncomeEntry generated by hbm2java
 */
public class IncomeEntry  implements java.io.Serializable {


     private Integer incomeId;
     private BsSubHead bsSubHead;
     private BsHead bsHead;
     private UserDetails userDetails;
     private UserAccountDetails userAccountDetails;
     private Date incomeDate;
     private double incomeAmount;
     private String incomeRemarks;
     private int relevantUser;

    public IncomeEntry() {
    }

	
    public IncomeEntry(BsSubHead bsSubHead, BsHead bsHead, double incomeAmount, int relevantUser) {
        this.bsSubHead = bsSubHead;
        this.bsHead = bsHead;
        this.incomeAmount = incomeAmount;
        this.relevantUser = relevantUser;
    }
    public IncomeEntry(BsSubHead bsSubHead, BsHead bsHead, UserDetails userDetails, UserAccountDetails userAccountDetails, Date incomeDate, double incomeAmount, String incomeRemarks, int relevantUser) {
       this.bsSubHead = bsSubHead;
       this.bsHead = bsHead;
       this.userDetails = userDetails;
       this.userAccountDetails = userAccountDetails;
       this.incomeDate = incomeDate;
       this.incomeAmount = incomeAmount;
       this.incomeRemarks = incomeRemarks;
       this.relevantUser = relevantUser;
    }
   
    public Integer getIncomeId() {
        return this.incomeId;
    }
    
    public void setIncomeId(Integer incomeId) {
        this.incomeId = incomeId;
    }
    public BsSubHead getBsSubHead() {
        return this.bsSubHead;
    }
    
    public void setBsSubHead(BsSubHead bsSubHead) {
        this.bsSubHead = bsSubHead;
    }
    public BsHead getBsHead() {
        return this.bsHead;
    }
    
    public void setBsHead(BsHead bsHead) {
        this.bsHead = bsHead;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public UserAccountDetails getUserAccountDetails() {
        return this.userAccountDetails;
    }
    
    public void setUserAccountDetails(UserAccountDetails userAccountDetails) {
        this.userAccountDetails = userAccountDetails;
    }
    public Date getIncomeDate() {
        return this.incomeDate;
    }
    
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }
    public double getIncomeAmount() {
        return this.incomeAmount;
    }
    
    public void setIncomeAmount(double incomeAmount) {
        this.incomeAmount = incomeAmount;
    }
    public String getIncomeRemarks() {
        return this.incomeRemarks;
    }
    
    public void setIncomeRemarks(String incomeRemarks) {
        this.incomeRemarks = incomeRemarks;
    }
    public int getRelevantUser() {
        return this.relevantUser;
    }
    
    public void setRelevantUser(int relevantUser) {
        this.relevantUser = relevantUser;
    }




}


