package com.balance.hib.bean;
// Generated 11 Dec, 2012 7:03:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Transfer generated by hbm2java
 */
public class Transfer  implements java.io.Serializable {


     private int transferId;
     private BsHead bsHead;
     private UserAccountDetails userAccountDetailsByTransferSaccount;
     private UserDetails userDetails;
     private UserAccountDetails userAccountDetailsByTransferDaccount;
     private Date transferDate;
     private double transferAmount;
     private String transferRemarks;

    public Transfer() {
    }

	
    public Transfer(int transferId, BsHead bsHead, double transferAmount) {
        this.transferId = transferId;
        this.bsHead = bsHead;
        this.transferAmount = transferAmount;
    }
    public Transfer(int transferId, BsHead bsHead, UserAccountDetails userAccountDetailsByTransferSaccount, UserDetails userDetails, UserAccountDetails userAccountDetailsByTransferDaccount, Date transferDate, double transferAmount, String transferRemarks) {
       this.transferId = transferId;
       this.bsHead = bsHead;
       this.userAccountDetailsByTransferSaccount = userAccountDetailsByTransferSaccount;
       this.userDetails = userDetails;
       this.userAccountDetailsByTransferDaccount = userAccountDetailsByTransferDaccount;
       this.transferDate = transferDate;
       this.transferAmount = transferAmount;
       this.transferRemarks = transferRemarks;
    }
   
    public int getTransferId() {
        return this.transferId;
    }
    
    public void setTransferId(int transferId) {
        this.transferId = transferId;
    }
    public BsHead getBsHead() {
        return this.bsHead;
    }
    
    public void setBsHead(BsHead bsHead) {
        this.bsHead = bsHead;
    }
    public UserAccountDetails getUserAccountDetailsByTransferSaccount() {
        return this.userAccountDetailsByTransferSaccount;
    }
    
    public void setUserAccountDetailsByTransferSaccount(UserAccountDetails userAccountDetailsByTransferSaccount) {
        this.userAccountDetailsByTransferSaccount = userAccountDetailsByTransferSaccount;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public UserAccountDetails getUserAccountDetailsByTransferDaccount() {
        return this.userAccountDetailsByTransferDaccount;
    }
    
    public void setUserAccountDetailsByTransferDaccount(UserAccountDetails userAccountDetailsByTransferDaccount) {
        this.userAccountDetailsByTransferDaccount = userAccountDetailsByTransferDaccount;
    }
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }
    public double getTransferAmount() {
        return this.transferAmount;
    }
    
    public void setTransferAmount(double transferAmount) {
        this.transferAmount = transferAmount;
    }
    public String getTransferRemarks() {
        return this.transferRemarks;
    }
    
    public void setTransferRemarks(String transferRemarks) {
        this.transferRemarks = transferRemarks;
    }




}


