package com.balance.hib.bean;
// Generated 24 Jul, 2012 10:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserAccountDetails generated by hbm2java
 */
public class UserAccountDetails  implements java.io.Serializable {


     private int userAccountId;
     private BsHead bsHead;
     private BsSubHead bsSubHead;
     private UserDetails userDetails;
     private String userAccountName;
     private String userAccountBankName;
     private String userAccountBankBranch;
     private String userAccountNo;
     private Long openingBalance;
     private Set<ExpenseEntry> expenseEntries = new HashSet<ExpenseEntry>(0);
     private Set<IncomeEntry> incomeEntries = new HashSet<IncomeEntry>(0);
     private Set transfersForTransferDaccount = new HashSet(0);
     private Set transfersForTransferSaccount = new HashSet(0);
     
      public BsSubHead getBsSubHead() {
        return bsSubHead;
    }

    public void setBsSubHead(BsSubHead bsSubHead) {
        this.bsSubHead = bsSubHead;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UserAccountDetails other = (UserAccountDetails) obj;
        if (this.userAccountId != other.userAccountId) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + this.userAccountId;
        return hash;
    }
     
    public Set getTransfersForTransferDaccount() {
        return transfersForTransferDaccount;
    }

    public void setTransfersForTransferDaccount(Set transfersForTransferDaccount) {
        this.transfersForTransferDaccount = transfersForTransferDaccount;
    }

    public Set getTransfersForTransferSaccount() {
        return transfersForTransferSaccount;
    }

    public void setTransfersForTransferSaccount(Set transfersForTransferSaccount) {
        this.transfersForTransferSaccount = transfersForTransferSaccount;
    }

    public UserAccountDetails() {
    }

	
    public UserAccountDetails(int userAccountId, UserDetails userDetails, String userAccountName, String userAccountBankName, String userAccountBankBranch) {
        this.userAccountId = userAccountId;
        this.userDetails = userDetails;
        this.userAccountName = userAccountName;
        this.userAccountBankName = userAccountBankName;
        this.userAccountBankBranch = userAccountBankBranch;
    }
    public UserAccountDetails(int userAccountId, BsHead bsHead, UserDetails userDetails, String userAccountName, String userAccountBankName, String userAccountBankBranch, String userAccountNo, Long openingBalance, Set<ExpenseEntry> expenseEntries, Set<IncomeEntry> incomeEntries) {
       this.userAccountId = userAccountId;
       this.bsHead = bsHead;
       this.userDetails = userDetails;
       this.userAccountName = userAccountName;
       this.userAccountBankName = userAccountBankName;
       this.userAccountBankBranch = userAccountBankBranch;
       this.userAccountNo = userAccountNo;
       this.openingBalance = openingBalance;
       this.expenseEntries = expenseEntries;
       this.incomeEntries = incomeEntries;
    }
   
    public int getUserAccountId() {
        return this.userAccountId;
    }
    
    public void setUserAccountId(int userAccountId) {
        this.userAccountId = userAccountId;
    }
    public BsHead getBsHead() {
        return this.bsHead;
    }
    
    public void setBsHead(BsHead bsHead) {
        this.bsHead = bsHead;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public String getUserAccountName() {
        return this.userAccountName;
    }
    
    public void setUserAccountName(String userAccountName) {
        this.userAccountName = userAccountName;
    }
    public String getUserAccountBankName() {
        return this.userAccountBankName;
    }
    
    public void setUserAccountBankName(String userAccountBankName) {
        this.userAccountBankName = userAccountBankName;
    }
    public String getUserAccountBankBranch() {
        return this.userAccountBankBranch;
    }
    
    public void setUserAccountBankBranch(String userAccountBankBranch) {
        this.userAccountBankBranch = userAccountBankBranch;
    }
    public String getUserAccountNo() {
        return this.userAccountNo;
    }
    
    public void setUserAccountNo(String userAccountNo) {
        this.userAccountNo = userAccountNo;
    }
    public Long getOpeningBalance() {
        return this.openingBalance;
    }
    
    public void setOpeningBalance(Long openingBalance) {
        this.openingBalance = openingBalance;
    }
    public Set<ExpenseEntry> getExpenseEntries() {
        return this.expenseEntries;
    }
    
    public void setExpenseEntries(Set<ExpenseEntry> expenseEntries) {
        this.expenseEntries = expenseEntries;
    }
    public Set<IncomeEntry> getIncomeEntries() {
        return this.incomeEntries;
    }
    
    public void setIncomeEntries(Set<IncomeEntry> incomeEntries) {
        this.incomeEntries = incomeEntries;
    }




}


